Update `--version`
eunomia-bpf/eunomia-bpf pull request #106
Opened 2023-01-22 08:46 UTC by Officeyutong

https://github.com/eunomia-bpf/eunomia-bpf/issues/41

2023-01-22 09:19 UTC, yunwei37 requested changes

2023-01-22 09:19 UTC, yunwei37 commented on ecli/src/main.cpp
> +// #include "../../third_party/bpftool/libbpf/src/libbpf.h"
尽量不要有这种没有意义的被注释掉的代码?

2023-01-22 09:19 UTC, yunwei37 commented on ecli/src/main.cpp
> -{
这些没啥意义的修改可以去掉，这样 review 起来会更方便一点?

2023-01-22 09:19 UTC, yunwei37 commented on ecli/src/main.cpp
> +const char* ECLI_VERSION = "1.0";
这个 version 可以 include 这个文件: https://github.com/eunomia-bpf/eunomia-bpf/blob/master/VERSION

把 ecli version 换成 eunomia-bpf version 吧，比如说这样:

eunomia-bpf version: 0.3.0

2023-01-22 09:19 UTC, yunwei37 commented on ecli/src/main.cpp
> +        using std::cerr;
把这个部分抽象成一个函数出来，放在这里: https://github.com/eunomia-bpf/eunomia-bpf/blob/master/bpf-loader/src/eunomia_bpf.cpp

这个函数返回一个 string 描述所有的 version 信息

2023-01-22 09:19 UTC, yunwei37 commented on ecli/src/main.cpp
> +    } catch (const std::runtime_error& err) {
这样的修改也可以去掉?

2023-01-22 09:31 UTC, Officeyutong commented on ecli/src/main.cpp
> -{
草，这个是clang-format给我格式化的，我没注意

2023-01-23 04:36 UTC, yunwei37 requested changes

2023-01-23 04:36 UTC, yunwei37 commented on bpf-loader/src/eunomia_bpf.cpp
> +std::string get_eunomia_version() {
Add tests for the new function in bpf-loader to pass CI

See https://github.com/eunomia-bpf/eunomia-bpf/blob/master/bpf-loader/test/src/config_test.cpp

You may add a new function to test in this file.

Run `make test` in bpf-loader dir to test.

2023-01-23 06:25 UTC, yunwei37 approved these changes

2023-01-23 06:29 UTC, merged