add xdp example
eunomia-bpf/eunomia-bpf pull request #223
Opened 2023-05-08 11:13 UTC by CH3CHOHCH3

# add xdp support

Fixes #218 

## Description

Add xdp type support for bpf-loader-lib by APIs of [libbpf_sys](https://docs.rs/libbpf-sys/latest/libbpf_sys/):

- [bpf_xdp_attach](https://docs.rs/libbpf-sys/latest/libbpf_sys/fn.bpf_xdp_attach.html)
- [bpf_xdp_detach](https://docs.rs/libbpf-sys/latest/libbpf_sys/fn.bpf_xdp_detach.html)

According to the argument list of [bpf_xdp_attach](https://docs.rs/libbpf-sys/latest/libbpf_sys/fn.bpf_xdp_attach.html) and the definition of [bpf_xdp_attach_opts](https://docs.rs/libbpf-sys/latest/libbpf_sys/struct.bpf_xdp_attach_opts.html), we can use

```C
/// @xdphook {"ifindex":1}
/// @xdpopts {"old_prog_fd":"0"}
```
to pass parameters to bpf-loader-lib and the latter will use [libbpf_sys](https://github.com/eunomia-bpf/eunomia-bpf/blob/master/bpf-loader-rs/bpf-loader-lib/src/skeleton/preload/attach.rs#L9) to implement attach.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

2023-05-09 21:18 UTC, yunwei37 requested changes
please add a readme.md for the xdp example, include how to run it and the results.

2023-05-09 23:56 UTC, Officeyutong requested changes
Seems that the CI fails to run on your example. You should fix that

2023-05-10 02:30 UTC, Officeyutong requested changes
Please add tests on attaching & detaching xdp programs

2023-05-10 02:44 UTC, Officeyutong commented on bpf-loader-rs/bpf-loader-lib/src/skeleton/preload/attach.rs
> +pub(crate) fn attach_xdp(program: &Program, meta: &ProgMeta) -> Result<AttachLink> {
libbpf-rs provides APIs to attach XDP. https://docs.rs/libbpf-rs/latest/libbpf_rs/struct.Program.html#method.attach_xdp . is this suitable for us?

2023-05-10 02:49 UTC, Officeyutong requested changes

2023-05-10 02:49 UTC, Officeyutong commented on bpf-loader-rs/bpf-loader-lib/src/skeleton/preload/attach.rs
> +    let err = unsafe { bpf_xdp_attach(ifindex, prog_fd, flags, &*xdp_attach_opts) };
Unsafe blocks should be described with a "//SAFETY:" comment to provide a brief description on what this unsafe call does and why this unsafe call is "safe"

2023-05-10 02:49 UTC, Officeyutong commented on bpf-loader-rs/bpf-loader-lib/src/skeleton/preload/attach.rs
> +    let err = unsafe { bpf_xdp_attach(ifindex, prog_fd, flags, &*xdp_attach_opts) };
See other unsafe calls for reference

2023-05-10 08:46 UTC, Officeyutong commented on bpf-loader-rs/bpf-loader-lib/src/skeleton/preload/attach.rs
> +pub(crate) fn attach_xdp(program: &Program, meta: &ProgMeta) -> Result<AttachLink> {
It's not suitable

2023-05-13 04:10 UTC, Officeyutong approved these changes

2023-05-13 10:42 UTC, merged