Ymeunomia bpf
eunomia-bpf/eunomia-bpf pull request #94
Opened 2023-01-10 06:44 UTC by saivian1

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-01-11 16:29 UTC, yunwei37 commented
you need to rebase it on master branch.

2023-01-11 16:31 UTC, yunwei37 requested changes
是不是构建不成功?

2023-01-11 16:31 UTC, yunwei37 commented on bpf-loader/test/src/file.c
> +
这个测试是用来做什么的?

2023-01-12 05:04 UTC, yunwei37 requested changes

2023-01-12 05:04 UTC, yunwei37 commented on bpf-loader/test/src/arg_parser_test.cpp
> +            == -1);
你需要找到原因，为什么这些测试会挂掉？而不是测试挂了去修改测试结果，这样的测试没有任何意义

2023-01-12 05:04 UTC, yunwei37 commented on bpf-loader/src/trace_helpers.c
> +      // 如果没有单词，则跳过
不要用中文注释

2023-01-12 05:04 UTC, yunwei37 commented on bpf-loader/test/src/file1.txt
> +gcc -o file.elf file.c
file.elf 和 file.txt 放到 assert 里面去，把代码和这种测试数据放在一起不是很好的习惯

2023-01-16 15:18 UTC, saivian1 commented
1.16

1. 确认你本地的代码和远程分支是否一样? force push 了没有?
不一样，已经force push

2. 新加的库去掉了嘛? 确认一下是否有必要用别的库? 能不用就不用

总共有两个新库，<climits>，<sys/stat.h>
第一个库已经去掉，第二个库是必须的，用stat()去替换open()去检查文件是否存在，类型，访问权限等问题。可以避免code risk
3. fentry_can_attach 的问题是在 libbpf 里面，我可以帮你看看，这个不是我们自己写的
定位到btf.c中的
__u32 btf__type_cnt(const struct btf *btf)
{
    return btf->start_id + btf->nr_types;
}
btf数据类型是在btf.h中定义，在btf.c中头文件是#include "bpf.h",   在trace_helpers.c中 btf类型数据是在#include <linux/btf.h>中定义.分析结果可能是这两个头文件中定义的btf类型结构体有一些差异，导致在上述函数中这个访问操作（btf->start_id + btf->nr_types）发生访问无效地址，进而导致程序奔溃。

解决，换#include <linux/btf.h>头文件为#include <bpf/btf.h>，问题得到解决。

2023-01-16 15:32 UTC, yunwei37 requested changes

2023-01-16 15:32 UTC, yunwei37 commented on hello.bpf.c
> +#define BPF_NO_GLOBAL_DATA
这个文件是用来做什么的呢?

2023-01-16 15:32 UTC, yunwei37 commented on bpf-loader/include/eunomia/eunomia-bpf.hpp
> -  private:
这里为什么需要更改?

2023-01-16 15:32 UTC, yunwei37 commented on bpf-loader/test/src/helpers_test.cpp
> +    e = open_elf_by_fd(INT_MIN);
这里为什么要复制这么多遍?

2023-01-16 15:32 UTC, yunwei37 commented on bpf-loader/test/src/helpers_test.cpp
> +    e = open_elf_by_fd(INT_MIN);
为什么这里会重复很多遍这个?

2023-01-16 15:32 UTC, yunwei37 commented on hello.bpf.c
> +#include <linux/bpf.h>
这个 hello.bpf.c 是拿来做什么的?

2023-01-16 15:36 UTC, yunwei37 commented
1. 目前测试还是不通过，你看看这是什么原因? 是不是因为你的开发机是 arm 架构的，而 test 是 x86 架构的? 

目前我们使用了预编译的 JSON 文件作为测试用例，在测试的时候使用 ecc 根据当前的机器架构进行编译，可以解决这个问题，即在测试里面使用 makefile 和 bpf.c 文件，然后现场编译。

2. 我留了一些代码审查结果，请有空回复一下。

2023-01-16 15:44 UTC, saivian1 commented on bpf-loader/include/eunomia/eunomia-bpf.hpp
> -  private:
失误

2023-01-23 08:58 UTC, yunwei37 commented
Thanks！I fix some remain issues myself.

2023-01-23 09:14 UTC, yunwei37 approved these changes

2023-01-23 09:14 UTC, merged